### ISSUE TITLE
`sphinxcontrib-spelling==5.1.0` + `Sphinx==3.1.0` explode under Python 3.7

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/spelling#49]
Here's the log: https://github.com/cherrypy/cheroot/pull/291/checks?check_run_id=761123275#step:9:211.

I also have a green job "from before" that uses `sphinxcontrib-spelling==5.0.0` + `Sphinx==3.0.3`. I don't yet know what exactly causes this issue but I assume it's one of these. I must mention that this job is isolated to only run spelling and doesn't affect any other tests.

```python-traceback
spellcheck-docs run-test: commands[2] | python -m sphinx -j auto -a -n -W -b spelling --color -d /home/runner/work/cheroot/cheroot/.tox/docs_doctree . /home/runner/work/cheroot/cheroot/.tox/docs_out
Running Sphinx v3.1.0
Initializing Spelling Checker
making output directory... done
Ignoring wiki words
Ignoring acronyms
Adding package names from PyPI to local dictionary…
Ignoring Python builtins
Ignoring importable module names
Adding contents of /home/runner/work/cheroot/cheroot/docs/spelling_wordlist.txt to custom word list
Looking for custom word list in /tmp/tmp72ct6ygm/spelling_wordlist.txt
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.python.org/2/objects.inv...
loading intersphinx inventory from https://docs.cherrypy.org/en/latest/objects.inv...
loading intersphinx inventory from https://trustme.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://ddt.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://www.pyopenssl.org/en/latest/objects.inv...
building [mo]: all of 0 po files
building [spelling]: all source files
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [ 50%] contribute .. pkg/cheroot.server                     
/home/runner/work/cheroot/cheroot/.tox/spellcheck-docs/lib/python3.7/site-packages/sphinx_tabs/tabs.py:341: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript(path)
reading sources... [100%] pkg/cheroot.ssl .. pkg/cheroot.wsgi                  
waiting for workers...
Process Process-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/cheroot/cheroot/.tox/spellcheck-docs/lib/python3.7/site-packages/sphinx/util/parallel.py", line 91, in _process
    pipe.send((failed, collector.logs, ret))
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle traceback objects
Process Process-2:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/cheroot/cheroot/.tox/spellcheck-docs/lib/python3.7/site-packages/sphinx/util/parallel.py", line 91, in _process
    pipe.send((failed, collector.logs, ret))
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle traceback objects

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
The full traceback has been saved in /tmp/sphinx-err-7ul4u898.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by webknjaz** [comment]
Alright, I've found a job with `Sphinx==3.0.4` + `sphinxcontrib-spelling==5.1.0` that succeeds. So it's probably a regression of Sphinx but I'll keep this open for now.

**Comment by webknjaz** [comment]
Looks like this is a regression https://github.com/sphinx-doc/sphinx/issues/7802.
