### ISSUE TITLE
The extension is not found when used in readthedocs

### ISSUE THREAD

**Issue by Lezcano** [sphinx-contrib/spelling#98]
When using this extension and uploading the documentation to readthedocs.org, I keep getting the following error:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 409, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.spelling'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geotorch/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 413, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.spelling (exception: No module named 'sphinxcontrib.spelling')

Extension error:
Could not import extension sphinxcontrib.spelling (exception: No module named 'sphinxcontrib.spelling')
```

On the other hand, I saw that, as of v.5.2.0, `sphinx-contrib/spelling` supports readthedocs.org 

Is this a known issue?

The project on which I am finding this behaviour is:
https://github.com/Lezcano/geotorch

**Comment by dhellmann** [comment]
Have you configured readthedocs.org to install the documentation build dependencies for your project?

**Comment by Lezcano** [comment]
It was indeed a problem related to what you mention.
Thank you so much for the prompt reply!
